### ISSUE TITLE
ECONNREFUSED 127.0.0.1:55317

### ISSUE THREAD

**Issue by diachedelic** [piktur/vue-cli-plugin-e2e-webdriverio#4]
I am repeatedly getting this error, with the port number randomising each time:

```
$ yarn test --spec test/specs/login.js 
yarn run v1.10.1
warning package.json: No license field
$ vue-cli-service test:e2e --mode development --no-debug --headless --spec test/specs/login.js
ERROR: connect ECONNREFUSED 127.0.0.1:55317
chrome
    at new RuntimeError (/Users/me/Code/com10/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/Users/me/Code/com10/node_modules/webdriverio/build/lib/utils/RequestHandler.js:330:43)
    at self.callback (/Users/me/Code/com10/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/me/Code/com10/node_modules/request/request.js:881:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)

 ERROR  Command failed: /Users/me/Code/com10/node_modules/webdriverio/bin/wdio --spec test/specs/login.js --baseUrl http://localhost:8080 --port 55317 /Users/me/Code/com10/node_modules/vue-cli-plugin-e2e-webdriverio/wdio.conf.default.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It's only happening on one of two projects using this plugin.

**Comment by diachedelic** [comment]
Hold off, this may be fixed by nuking `node_modules`...

**Comment by diachedelic** [comment]
This fixed it:
```
rm -rf yarn.lock node_modules && yarn install
```

**Comment by diachedelic** [comment]
Just happens at random somewhere in the test suite

**Comment by diachedelic** [comment]
Output from `ps -ef` while everything is working, so I suppose it's the connection with Chromedriver that's being severed

```
  501 66280 66279   0  1:48pm ttys008    0:06.63 node /proj/node_modules/webdriverio/bin/wdio --baseUrl http://localhost:8009 --port 58310 /proj/node_modules/vue-cli-plugin-e2e-webdriverio/wdio.conf.default.js
  501 66281 66280   0  1:48pm ttys008    0:18.78 /proj/node_modules/chromedriver/lib/chromedriver/chromedriver --url-base=/wd/hub --port=58310 --proxy-server='direct://' --proxy-bypass -list=* --headless
  501 76144 66280   0  1:55pm ttys008    0:01.15 /Users/jamesdiacono/.nvm/versions/node/v8.12.0/bin/node /proj/node_modules/webdriverio/build/lib/runner.js --baseUrl http://localhost:8009 --port 58310 /proj/node_modules/vue-cli-plugin-e2e-webdriverio/wdio.conf.default.js
```

**Comment by diachedelic** [comment]
Seems kinda like it could be related to [this](https://github.com/atti187/wdio-chromedriver-service/issues/9)

**Comment by piktur** [comment]
@diachedelic Hey, you're on High Sierra aren't you? [wdio-chromedriver-service v0.1.5](https://github.com/atti187/wdio-chromedriver-service/commit/434ab36693f11f18dc435036396cb3457c66294b) includes a fix [434ab36](https://github.com/atti187/wdio-chromedriver-service/commit/434ab36693f11f18dc435036396cb3457c66294b). Could you peg `wdio-chromedriver-service` at `0.1.5` within local `package.json`. 

If problem persists after upgrade, set `config.logLevel` to `'verbose'` within `wdio.config.js` and report back.

**Comment by diachedelic** [comment]
Looks like that might have done it, I'll submit a fix to this lib

**Comment by piktur** [comment]
Cheers

**Comment by diachedelic** [comment]
Ok done, reckon you could publish to npm?  cheers!

**Comment by piktur** [comment]
No probs, published. Apologies for the delay, only became aware of this today. Reopen if it crops up again.
